.travis.yml
Turns out I don't really know how to write Python 3 compatible exceptions :dancer:
=> travis: add configuration file

inspire_matcher/api.py
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> api: return result hits

.travis.yml, inspire_matcher/api.py, inspire_matcher/core.py, tests/test_api.py
Closes https://github.com/inspirehep/inspire-matcher/issues/5.
=> global: support Python 3

inspire_matcher/core.py, tests/test_core.py
Closes https://github.com/inspirehep/inspire-matcher/issues/13.
=> global: support collections

inspire_matcher/core.py, tests/test_core.py
=> core: use match queries instead of term queries

inspire_matcher/core.py, tests/test_core.py
=> global: support nested queries

inspire_matcher/config.py, inspire_matcher/core.py, tests/test_api.py, tests/test_core.py
Closes https://github.com/inspirehep/inspire-matcher/issues/21.
=> api: match -> path, search -> search_path

inspire_matcher/core.py, tests/test_core.py
Adds back the fuzzy queries researched by @jmartinm in https://github.com/inspirehep/invenio-matcher-benchmark.
=> core: support fuzzy queries

inspire_matcher/api.py, setup.py, tests/test_api.py
Signed-off-by: David Caro <david@dcaro.es>
=> api: allow using callables as validators

setup.py
Prevents some errors while dealing with Unicode by adding the
``unicode-string-literal`` dependency, which adds an extra Flake8
check for Unicode-unsafe constructs.
=> global: add the unicode-string-literal dependency

inspire_matcher/api.py
I wish I could write more, but my train is leaving...
=> api: allow filtering the _source of the returned hit

.travis.yml, run-tests.sh, setup.py
Remove ``pytest-flake8`` and replace it with just ``flake8`` as the
former is sometimes not finding style violations present in the code.
=> global: don't use pytest-flake8

inspire_matcher/utils.py, inspire_matcher/validators.py, tests/test_utils.py, tests/test_validators.py
This is not done, please write suggestions without holding back!
=> Refactor authors titles validator for fuzzy matcher

.travis.yml, inspire_matcher/core.py, setup.py, tests/test_core.py
Signed-off-by: Szymon Łopaciuk <szymon@lopaciuk.eu>
=> global: update queries for ES5 migration

setup.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
Sem-ver: breaks compatibility
=> setup: bump inspire-json-merger

setup.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
Sem-Ver: breaks compatibility
=> setup: bump version

setup.cfg, setup.py
sem-ver: breaks compatibility
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
=> bump inspire utils and json-merger version

inspire_matcher/config.py
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
=> config: add source fields for the validator

inspire_matcher/validators.py, tests/fixtures/matching_result_2654944.json, tests/fixtures/matching_wrong_2654944.json
Signed-off-by: Victor Balbuena <vbalbp@gmail.com>
=> validators: fix item getter for cds match result

setup.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
Sem-Ver: breaks compatibility
=> setup: bump inspire-json-merger to v11.*

inspire_matcher/core.py, setup.py, tests/test_core.py
=> pubnote search: add prefix query for journal_name with volume

inspire_matcher/core.py, tests/test_core.py
=> pubnote search: prefix search for journal_title included in bool query

inspire_matcher/api.py
Ref: inspirehep/inspirehep#1412
=> api: use index prefix for matcher configs

inspire_matcher/core.py, tests/test_api.py, tests/test_core.py
Ref: inspirehep/inspirehep#1499
=> nested queries: add support for generating inner_hits

inspire_matcher/core.py, tests/test_core.py
Ref: inspirehep/inspirehep#1499
=> core: add author-names query

inspire_matcher/core.py, setup.py, tests/test_core.py
ref:inspirehep/inspirehep#2320
=> core: add operator to nested query

inspire_matcher/config.py, inspire_matcher/validators.py, tests/test_validators.py
ref:inspirehep/inspirehep#2328
=> config: add matching based on pids

inspire_matcher/api.py
ref: inspirehep/inspirehep#2334
=> api: add query size to query config

inspire_matcher/api.py, inspire_matcher/validators.py, tests/test_api.py
Ref: #https://github.com/inspirehep/inspirehep/issues/2377
=> validator: dont fuzzy match arxiv

inspire_matcher/utils.py, inspire_matcher/validators.py, setup.py, tests/test_utils.py
* Refs cern-sis/issues-inspire#23
=> Improve title validator

inspire_matcher/validators.py, tests/test_validators.py
* Ref: cern-sis/issues-inspire#29
=> validators: fix arxiv validator

inspire_matcher/utils.py, tests/test_utils.py
* ref: cern-sis/issues-inspire#314
=> utils: fix compute author match score

.github/workflows/bump-and-publish.yml, .github/workflows/lint.yml, .github/workflows/pull-request-master.yml, .github/workflows/test-python-2.yml, .github/workflows/test-python-3.yml, .pre-commit-config.yaml, README.rst, inspire_matcher/api.py, inspire_matcher/core.py, inspire_matcher/ext.py, inspire_matcher/validators.py, setup.py, tests/conftest.py, tests/test_api.py, tests/test_core.py, tests/test_validators.py
* ref https://github.com/cern-sis/issues-inspire/issues/886
=> setup: actions and deps

.github/workflows/bump-and-publish.yml
ref: https://github.com/cern-sis/issues-inspire/issues/1029
=> actions: fix package build
